############################################################
#
# Utility
#
############################################################

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'



############################################################
#
# Syntax highlighting - javascript + alpha
#
############################################################


[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'
hook_add = '''
	let g:javascript_plugin_jsdoc = 1
	let g:javascript_plugin_ngdoc = 1
	let g:javascript_plugin_flow = 1
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = 'vue'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = 'typescript'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = 'typescriptreact'
hook_add = '''
	autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescriptreact
'''

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = 'typescriptreact'
hook_add = '''
	autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescriptreact
'''



############################################################
#
# Syntax highlighting - html/css
#
############################################################

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss', 'sass']
hook_add = '''
	augroup VimCSS3Syntax
		autocmd!
		autocmd FileType css setlocal iskeyword+=-
	augroup END
'''



############################################################
#
# Syntax highlighting - toml
#
############################################################

[[plugins]]
repo ='cespare/vim-toml'
on_ft = 'toml'



############################################################
#
# Syntax highlighting - python
#
############################################################

[[plugins]]
repo = 'numirias/semshi'
on_ft = 'python'



